### ISSUE TITLE
Can't index field type array

### ISSUE THREAD

**Issue by arvindnr** [bricas/webservice-solr#29]
I need to index a array field. I passed the reference. It complains that 

The Field looks like the following :8ball: 
bless( {
                                        'value' => [
                                                     'Dancing'
                                                   ],
                                        'name' => 'doc_pref_lookingfor_txt'
                                      }, 'WebService::Solr::Field' ),

It complains saying that : invalid XML data: character data isn't a string

Please let me know how to index array.

Thanks
Arvind

**Comment by bricas** [comment]
If you're creating individual Field objects, then just loop through each of your values and create an object for each.

If you're creating a document object, then it will handle this for you:

```
my $d = WebService::Solr::Document->new( x => [1, 2, 3] );
```

Which gives:

```
$VAR1 = bless( {
                 'fields' => [
                               bless( {
                                        'name' => 'x',
                                        'value' => '1'
                                      }, 'WebService::Solr::Field' ),
                               bless( {
                                        'name' => 'x',
                                        'value' => '2'
                                      }, 'WebService::Solr::Field' ),
                               bless( {
                                        'value' => '3',
                                        'name' => 'x'
                                      }, 'WebService::Solr::Field' )
                             ]
               }, 'WebService::Solr::Document' );
```
